//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMi.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeMi.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de {0}.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur : Stéphane Mitermite
        ///Site web : http://freemiupnp.fr/.
        /// </summary>
        public static string AboutBox {
            get {
                return ResourceManager.GetString("AboutBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres avancés.
        /// </summary>
        public static string AdvancedParameters {
            get {
                return ResourceManager.GetString("AdvancedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoriser la suppression de fichiers (Freebox V5 uniquement).
        /// </summary>
        public static string AllowDeletion {
            get {
                return ResourceManager.GetString("AllowDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille du buffer (en kilo-octets).
        /// </summary>
        public static string BufferSize {
            get {
                return ResourceManager.GetString("BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to par défaut.
        /// </summary>
        public static string ByDefault {
            get {
                return ResourceManager.GetString("ByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler les modifications.
        /// </summary>
        public static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier si une nouvelle version est disponible au démarrage de l&apos;application.
        /// </summary>
        public static string CheckNewVersionAvailableAtStartup {
            get {
                return ResourceManager.GetString("CheckNewVersionAvailableAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom personnalisé pour le serveur.
        /// </summary>
        public static string CustomFriendlyName {
            get {
                return ResourceManager.GetString("CustomFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppr..
        /// </summary>
        public static string DeleteGestureText {
            get {
                return ResourceManager.GetString("DeleteGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemiupnp.fr/download.html.
        /// </summary>
        public static string DownloadWebPage {
            get {
                return ResourceManager.GetString("DownloadWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorateur de fichiers.
        /// </summary>
        public static string FileExplorer {
            get {
                return ResourceManager.GetString("FileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé du dossier :.
        /// </summary>
        public static string FolderLabel {
            get {
                return ResourceManager.GetString("FolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin du dossier :.
        /// </summary>
        public static string FolderPath {
            get {
                return ResourceManager.GetString("FolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossiers.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freebox V5.
        /// </summary>
        public static string FreeboxV5 {
            get {
                return ResourceManager.GetString("FreeboxV5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freebox V6 (ou autre client UPnP).
        /// </summary>
        public static string FreeboxV6OrOtherUPnPClient {
            get {
                return ResourceManager.GetString("FreeboxV6OrOtherUPnPClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support de l&apos;IPv6.
        /// </summary>
        public static string IPv6Support {
            get {
                return ResourceManager.GetString("IPv6Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de média.
        /// </summary>
        public static string MediaKind {
            get {
                return ResourceManager.GetString("MediaKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux réseau.
        /// </summary>
        public static string NetworkStream {
            get {
                return ResourceManager.GetString("NetworkStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une nouvelle version est disponible !.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une nouvelle version de {0} est disponible ({1}). Vous possédez actuellement la version {2}.
        ///Souhaitez-vous consulter la page des téléchargements ?.
        /// </summary>
        public static string NewVersionAvailableMessage {
            get {
                return ResourceManager.GetString("NewVersionAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast.
        /// </summary>
        public static string Podcast {
            get {
                return ResourceManager.GetString("Podcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse du podcast :.
        /// </summary>
        public static string PodcastAddress {
            get {
                return ResourceManager.GetString("PodcastAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé du podcast :.
        /// </summary>
        public static string PodcastLabel {
            get {
                return ResourceManager.GetString("PodcastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez sur &lt;Entrée&gt; pour quitter.
        /// </summary>
        public static string PressEnterToQuit {
            get {
                return ResourceManager.GetString("PressEnterToQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveur redémarré.
        /// </summary>
        public static string RestartedServer {
            get {
                return ResourceManager.GetString("RestartedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RestartHS {
            get {
                object obj = ResourceManager.GetObject("RestartHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redémarrer le serveur.
        /// </summary>
        public static string RestartServer {
            get {
                return ResourceManager.GetString("RestartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer au démarrage de Windows.
        /// </summary>
        public static string RunAtWindowsStartup {
            get {
                return ResourceManager.GetString("RunAtWindowsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu &apos;Arrêter l&apos;ordinateur&apos;.
        /// </summary>
        public static string ShutdownMenu {
            get {
                return ResourceManager.GetString("ShutdownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse du flux :.
        /// </summary>
        public static string StreamAddress {
            get {
                return ResourceManager.GetString("StreamAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé du flux :.
        /// </summary>
        public static string StreamLabel {
            get {
                return ResourceManager.GetString("StreamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port TCP (0 = port dynamique).
        /// </summary>
        public static string TCPPort {
            get {
                return ResourceManager.GetString("TCPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemiupnp.fr/download/version.txt.
        /// </summary>
        public static string VersionFileUrl {
            get {
                return ResourceManager.GetString("VersionFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vidéo.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemiupnp.fr/.
        /// </summary>
        public static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
    }
}
